### ISSUE TITLE
CURL_TIMEOUT issues

### ISSUE THREAD

**Issue by cardmagic** [CenturyLinkLabs/building#4]
It seems that each of the Heroku buildpacks use the --max-time option in curl for some reason, and they are all really small. In Ruby's case, it was set to 30 seconds which was not enough time on my home internet connection to download the bundler cache. With the Ruby buildpack specifically, that value can be overridden with the CURL_TIMEOUT env var, but it's different for each language pack. It took me a really long time to figure this out, and ultimately I just used an ENV step in a Docker.include file in my repo to fix it but I was wondering if perhaps this should be documented better or maybe even include a new switch or some auto-magical thing in building that takes care of this for each of the different language packs.

**Comment by rossjimenez** [comment]
Closing
